export const CONTACTS_FETCH_REQUEST = 'CONTACTS_FETCH_REQUEST';
export const CONTACTS_FETCH_SUCCESS = 'CONTACTS_FETCH_SUCCESS';
export const CONTACTS_FETCH_FAILURE = 'CONTACTS_FETCH_FAILURE';

export const CONTACTS_SEARCH = 'CONTACTS_SEARCH';

export const CONTACTS_ADD_REQUEST = 'CONTACTS_ADD_REQUEST';
export const CONTACTS_ADD_SUCCESS = 'CONTACTS_ADD_SUCCESS';
export const CONTACTS_ADD_FAILURE = 'CONTACTS_ADD_FAILURE';

export const CONTACTS_EDIT_REQUEST = 'CONTACTS_EDIT_REQUEST';
export const CONTACTS_EDIT_SUCCESS = 'CONTACTS_EDIT_SUCCESS';
export const CONTACTS_EDIT_FAILURE = 'CONTACTS_EDIT_FAILURE';

export const CONTACTS_DELETE_REQUEST = 'CONTACTS_DELETE_REQUEST';
export const CONTACTS_DELETE_SUCCESS = 'CONTACTS_DELETE_SUCCESS';
export const CONTACTS_DELETE_FAILURE = 'CONTACTS_DELETE_FAILURE';